### ISSUE TITLE
Either Enable the app to run on android 9 or do not support android 9.

### ISSUE THREAD

**Issue by MichaelMcCulloch** [MichaelMcCulloch/WhisperVoiceKeyboard#3]
```
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "AAudioStreamBuilder_setAllowedCapturePolicy" referenced by "/data/app/com.mjm.WhisperVoiceKeyboard-a3E7sp5GnVQLFshcTaEkbA==/base.apk!/lib/x86_64/librust.so
```
```
no method named `allowed_capture_policy` found for struct `AudioStreamBuilder` in the current scope
method not found in `AudioStreamBuilder`
```

Evidently, in android 9 (api 28) and below, there's no API to set the value of this field. Setting this to false prevents system and third party apps from capturing the audio. [This](https://android-developers.googleblog.com/2019/07/capturing-audio-in-android-q.html) source indicates the default is true.

**Comment by mcmaillet** [comment]
Temporary branch that removes setting the "allowed capture policy" so it can work on Android 9. Ideally there would be a setting to control.

**Comment by appsoft124** [comment]
> Temporary branch that removes setting the "allowed capture policy" so it can work on Android 9. Ideally there would be a setting to control.

i need your help can you send me your email ?

**Comment by appsoft124** [comment]
> 

have u fixed this issue?

**Comment by mcmaillet** [comment]
Yeah it was fixed, it works on android 9

**Comment by appsoft124** [comment]
> Yeah it was fixed, it works on android 9

and android 7  8 ? can you send me your email please ?

**Comment by MichaelMcCulloch** [comment]
Due to hardware and API limitations, this app will not function on android 7 or 8. You can reach me here easily enough.

Regards,

Michael McCulloch

**Comment by appsoft124** [comment]
> Due to hardware and API limitations, this app will not function on android 7 or 8. You can reach me here easily enough. Regards, Michael McCulloch

i want to chat you private please i give you my email 

mominit8@gmail.com
please message me here

**Comment by MichaelMcCulloch** [comment]
> Temporary branch that removes setting the "allowed capture policy" so it can work on Android 9. Ideally there would be a setting to control.

Closing issue

**Comment by mcmaillet** [comment]
Don't know about 7 or 8. ***@***.***
