### ISSUE TITLE
User-Install?

### ISSUE THREAD

**Issue by IzzySoft** [MichaelMcCulloch/WhisperVoiceKeyboard#6]
Just wondering, as it's not clear from the description: Is this an app for the end-user to install (and if so, where can the APK be found, and does it work fully offline as the permissions in the Manifest suggest) – or rather something for developers to include as library with their apps?

**Comment by MichaelMcCulloch** [comment]
Is this an app for the end-user to install? Yes. right now, its a DIY, some-assembly-required, serve yourself etc approach, but...
 where can the APK be found? on the play store, in the near future. Almost certainly
 and does it work fully offline as the permissions in the Manifest suggest? Yes, you can verify that yourself.

**Comment by IzzySoft** [comment]
That was fast, thanks! Then I wait for the future to arrive (soon a new year starts :see_no_evil:). Maybe you then also consider making the APK available as attachment to the corresponding release, for those not having access to Google's walled garden?
